use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Default, Debug)]
pub struct Genre {
    pub id: u64,

    #[serde(default)]
    pub name: String,

    #[serde(default)]
    pub slug: String,

    #[serde(default)]
    pub url: String,
}

#[derive(Serialize, Deserialize, Default, Clone, Debug)]
pub enum EspyGenre {
    #[default]
    Unknown,

    // Adventure
    PointAndClick,
    Action,
    IsometricAction,
    NarrativeAdventure,
    SurvivalAdventure,
    PuzzleAdventure,
    WalkingSimulator,

    // Arcade
    Fighting,
    BeatEmUp,
    Pinball,
    CardAndBoard,
    Deckbuilder,

    // Casual
    LifeSim,
    FarmingSim,
    FishingSim,
    SailingSim,
    DatingSim,
    Puzzle,
    EndlessRunner,
    Rhythm,
    PartyGame,
    VisualNovel,
    Exploration,

    // Platformer
    SideScroller,
    Metroidvania,
    Platformer3d,
    ShooterPlatformer,
    PrecisionPlatformer,
    PuzzlePlatformer,

    // RPG
    CRPG,
    ARPG,
    ActionRpg,
    JRPG,
    FirstPersonRpg,
    TurnBasedRpg,
    RTwPRPG,
    DungeonCrawler,
    MMORPG,

    // Shooter
    FirstPersonShooter,
    TopDownShooter,
    ThirdPersonShooter,
    SpaceShooter,
    Shmup,
    BattleRoyale,

    // Simulator
    CityBuilder,
    Tycoon,
    GodGame,
    Racing,
    Sports,
    FlightSimulator,
    CombatSimulator,
    NavalSimulator,
    DrivingSimulator,
    Survival,

    // Strategy
    TurnBasedStrategy,
    RealTimeStrategy,
    TurnBasedTactics,
    RealTimeTactics,
    GradStrategy,
    FourX,
    TowerDefense,
    MOBA,
}

impl EspyGenre {
    pub fn from_description(description: &str) -> Self {
        match description {
            "Point & Click" => EspyGenre::PointAndClick,
            "Action" => EspyGenre::Action,
            "Isometric Action" => EspyGenre::IsometricAction,
            "Narrative Adventure" => EspyGenre::NarrativeAdventure,
            "Survival Adventure" => EspyGenre::SurvivalAdventure,
            "Puzzle Adventure" => EspyGenre::PuzzleAdventure,
            "Walking Simulator" => EspyGenre::WalkingSimulator,
            "Fighting" => EspyGenre::Fighting,
            "Beat\"em Up" => EspyGenre::BeatEmUp,
            "Pinball" => EspyGenre::Pinball,
            "Card & Board Game" => EspyGenre::CardAndBoard,
            "Deckbuilder" => EspyGenre::Deckbuilder,
            "Life Sim" => EspyGenre::LifeSim,
            "Farming Sim" => EspyGenre::FarmingSim,
            "Fishing Sim" => EspyGenre::FishingSim,
            "Sailing Sim" => EspyGenre::SailingSim,
            "Dating Sim" => EspyGenre::DatingSim,
            "Puzzle" => EspyGenre::Puzzle,
            "Endless Runner" => EspyGenre::EndlessRunner,
            "Rhythm" => EspyGenre::Rhythm,
            "Party Game" => EspyGenre::PartyGame,
            "Visual Novel" => EspyGenre::VisualNovel,
            "Exploration" => EspyGenre::Exploration,
            "Side Scroller" => EspyGenre::SideScroller,
            "Metroidvania" => EspyGenre::Metroidvania,
            "3D Platformer" => EspyGenre::Platformer3d,
            "Shooter Platformer" => EspyGenre::ShooterPlatformer,
            "Precision Platformer" => EspyGenre::PrecisionPlatformer,
            "Puzzle Platformer" => EspyGenre::PuzzlePlatformer,
            "CRPG" => EspyGenre::CRPG,
            "ARPG" => EspyGenre::ARPG,
            "Action RPG" => EspyGenre::ActionRpg,
            "JRPG" => EspyGenre::JRPG,
            "First Person RPG" => EspyGenre::FirstPersonRpg,
            "Turn Based RPG" => EspyGenre::TurnBasedRpg,
            "RTwP RPG" => EspyGenre::RTwPRPG,
            "Dungeon Crawler" => EspyGenre::DungeonCrawler,
            "MMORPG" => EspyGenre::MMORPG,
            "First Person Shooter" => EspyGenre::FirstPersonShooter,
            "Top-Down Shooter" => EspyGenre::TopDownShooter,
            "3rd Person Shooter" => EspyGenre::ThirdPersonShooter,
            "Space Shooter" => EspyGenre::SpaceShooter,
            "Shmup" => EspyGenre::Shmup,
            "Battle Royale" => EspyGenre::BattleRoyale,
            "City Builder" => EspyGenre::CityBuilder,
            "Tycoon" => EspyGenre::Tycoon,
            "God Game" => EspyGenre::GodGame,
            "Racing" => EspyGenre::Racing,
            "Sports" => EspyGenre::Sports,
            "Flight Simulator" => EspyGenre::FlightSimulator,
            "Combat Simulator" => EspyGenre::CombatSimulator,
            "Naval Simulator" => EspyGenre::NavalSimulator,
            "Driving Simulator" => EspyGenre::DrivingSimulator,
            "Survival" => EspyGenre::Survival,
            "Turn Based Strategy" => EspyGenre::TurnBasedStrategy,
            "Real-Time Strategy" => EspyGenre::RealTimeStrategy,
            "Turn Based Tactics" => EspyGenre::TurnBasedTactics,
            "Real-Time Tactics" => EspyGenre::RealTimeTactics,
            "Grand Strategy" => EspyGenre::GradStrategy,
            "4X" => EspyGenre::FourX,
            "Tower Defense" => EspyGenre::TowerDefense,
            "MOBA" => EspyGenre::MOBA,
            _ => EspyGenre::Unknown,
        }
    }
}

impl From<&str> for EspyGenre {
    fn from(s: &str) -> Self {
        match s {
            "PointAndClick" => EspyGenre::PointAndClick,
            "Action" => EspyGenre::Action,
            "IsometricAction" => EspyGenre::IsometricAction,
            "NarrativeAdventure" => EspyGenre::NarrativeAdventure,
            "SurvivalAdventure" => EspyGenre::SurvivalAdventure,
            "PuzzleAdventure" => EspyGenre::PuzzleAdventure,
            "WalkingSimulator" => EspyGenre::WalkingSimulator,
            "Fighting" => EspyGenre::Fighting,
            "BeatEmUp" => EspyGenre::BeatEmUp,
            "Pinball" => EspyGenre::Pinball,
            "CardAndBoard" => EspyGenre::CardAndBoard,
            "Deckbuilder" => EspyGenre::Deckbuilder,
            "LifeSim" => EspyGenre::LifeSim,
            "FarmingSim" => EspyGenre::FarmingSim,
            "FishingSim" => EspyGenre::FishingSim,
            "SailingSim" => EspyGenre::SailingSim,
            "DatingSim" => EspyGenre::DatingSim,
            "Puzzle" => EspyGenre::Puzzle,
            "EndlessRunner" => EspyGenre::EndlessRunner,
            "Rhythm" => EspyGenre::Rhythm,
            "PartyGame" => EspyGenre::PartyGame,
            "VisualNovel" => EspyGenre::VisualNovel,
            "Exploration" => EspyGenre::Exploration,
            "SideScroller" => EspyGenre::SideScroller,
            "Metroidvania" => EspyGenre::Metroidvania,
            "Platformer3d" => EspyGenre::Platformer3d,
            "ShooterPlatformer" => EspyGenre::ShooterPlatformer,
            "PrecisionPlatformer" => EspyGenre::PrecisionPlatformer,
            "PuzzlePlatformer" => EspyGenre::PuzzlePlatformer,
            "CRPG" => EspyGenre::CRPG,
            "ARPG" => EspyGenre::ARPG,
            "ActionRpg" => EspyGenre::ActionRpg,
            "JRPG" => EspyGenre::JRPG,
            "FirstPersonRpg" => EspyGenre::FirstPersonRpg,
            "TurnBasedRpg" => EspyGenre::TurnBasedRpg,
            "RTwPRPG" => EspyGenre::RTwPRPG,
            "DungeonCrawler" => EspyGenre::DungeonCrawler,
            "MMORPG" => EspyGenre::MMORPG,
            "FirstPersonShooter" => EspyGenre::FirstPersonShooter,
            "TopDownShooter" => EspyGenre::TopDownShooter,
            "ThirdPersonShooter" => EspyGenre::ThirdPersonShooter,
            "SpaceShooter" => EspyGenre::SpaceShooter,
            "Shmup" => EspyGenre::Shmup,
            "BattleRoyale" => EspyGenre::BattleRoyale,
            "CityBuilder" => EspyGenre::CityBuilder,
            "Tycoon" => EspyGenre::Tycoon,
            "GodGame" => EspyGenre::GodGame,
            "Racing" => EspyGenre::Racing,
            "Sports" => EspyGenre::Sports,
            "FlightSimulator" => EspyGenre::FlightSimulator,
            "CombatSimulator" => EspyGenre::CombatSimulator,
            "NavalSimulator" => EspyGenre::NavalSimulator,
            "DrivingSimulator" => EspyGenre::DrivingSimulator,
            "Survival" => EspyGenre::Survival,
            "TurnBasedStrategy" => EspyGenre::TurnBasedStrategy,
            "RealTimeStrategy" => EspyGenre::RealTimeStrategy,
            "TurnBasedTactics" => EspyGenre::TurnBasedTactics,
            "RealTimeTactics" => EspyGenre::RealTimeTactics,
            "GradStrategy" => EspyGenre::GradStrategy,
            "FourX" => EspyGenre::FourX,
            "TowerDefense" => EspyGenre::TowerDefense,
            "MOBA" => EspyGenre::MOBA,
            _ => EspyGenre::Unknown,
        }
    }
}
